### PR TITLE
Add packer template for Fedora 22

### PR DESCRIPTION
**Pull request by berendt**
Because of the deprecation of yum in Fedora 22 it is necessary to
provide duplicated scripts for yum and dnf.

Closes-Bug: #2

### CODE REVIEW

**Comment by berendt** [comment]
Testing x86_64 architecture with Packer 0.7.5 and Vagrant 1.7.2 using VirtualBox at the moment. Cannot test other architectures/providers.

**Comment by annawake** [comment]
Thanks - this is a good start - however, there is far too much code duplication to approve a merge.  It looks like you could make a variable called say "PKG_MGR" check if it's Fedora 22 and use dnf, otherwise use yum.  Even better, it seems like a packer variable called "pkg_mgr" would suffice and no need to have any logic.

I might have some time tomorrow to refactor the code.

Great job figuring out how to make Fedora 22 work with all the new dnf stuff!

**Comment by berendt** [comment]
This PR is not well tested at the moment. Avoiding the code duplication would be nice and introducing some kind of variable makes sense to me.  I will also have a look tomorrow.

**Comment by annawake** [comment]
First cut committed here: https://github.com/boxcutter/fedora/commit/d63aa8839ee1a4df841b44e2a49e662f03be544b

Did some test builds on VirtualBox and they seem to work - VMware and Parallels do not, so I'm filtering them out in the Makefile.

I just put the package manager in a packer variable.

The only extra thing I discovered is that you can't seem to specify packages out of the new "C Development Tools and Libraries" group with GCC 5.1 in it in a kickstart.  I'd prefer to pre-load all the packages in the kickstart, but I don't know how to do this for Fedora 22.  So I load the gcc stuff dynamically on Fedora 22.

**Comment by berendt** [comment]
Thanks for reworking and merging this.

**Pull request closed without merging**
